# - name: Get list of Nebulon mounted SCSI devs
#   ansible.builtin.shell:
#     mount | grep sd.\ | awk '{print $1}' | sort -u
#   changed_when: false
#   register: mounted_sd_devices

# - name: Set mounted SCSI device
#   ansible.builtin.set_fact:
#     mounted_linux_devices: "{{ mounted_sd_devices.stdout }}"

# - name: debug available devices
#   debug:
#     var: available_linux_devices

# # - name: debug mounted devices
# #   debug:
# #     var: mounted_linux_devices

# - name: debug mount options
#   debug:
#     msg: "{{ available_linux_devices }}"
#   when: "mounted_linux_devices in search('available_linux_devices')"

# - name: debug
#   debug:
#     var: ansible_devices

# - name: Initialize empty list for devices
#   set_fact:
#     storage_devices: []
#   no_log: true

# - name: Set Nebulon SCSI devices
#   set_fact:
#     storage_devices: "{{ storage_devices + [item.key] }}"
#   no_log: true
#   with_dict: "{{ ansible_devices }}"
#   when:
#     - item.value.host.startswith('Serial')
#     - item.key != "sda"

# ok: [server-10.tme.nebulon.com] => {
#     "storage_devices": [
#         "sdb",
#         "sdc"
#     ]
# }
# ok: [server-11.tme.nebulon.com] => {
#     "storage_devices": [
#         "sdb",
#         "sdc"
#     ]
# }
# ok: [server-12.tme.nebulon.com] => {
#     "storage_devices": [
#         "sdb"
#     ]
# }

# - name: debug devices
#   debug:
#     var: storage_devices



# - name: Find Linux SCSI devs for new volumes
#   ansible.builtin.command:
#     lsscsi -u -b
#   register: lsscsi_result
#   changed_when: false

# Example return for lsscsi -u -b
# root@server-10:~# lsscsi -u -b
# [0:0:0:0]    6f497c20082e9f4f000ab00000001000  /dev/sda
# [0:0:0:2]    6f497c20082ea202000ab00000005000  /dev/sdb
# [0:0:0:3]    6f497c20082ea2b2000ab00000006000  /dev/sdc
# [0:0:0:254]  6f497c200000000000000000000000fe  -

# We have the candiate SD devices to use here:
# ok: [server-10.tme.nebulon.com] => {
#     "available_linux_devices": "/dev/sdc"
# }
# ok: [server-11.tme.nebulon.com] => {
#     "available_linux_devices": "/dev/sdc"
# }
# ok: [server-12.tme.nebulon.com] => {
#     "available_linux_devices": "/dev/sdb"
# }